# Generated by Django 5.2.4 on 2025-07-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Главный администратор'), ('autoservice_admin', 'Администратор автосервиса'), ('manager', 'Менеджер'), ('client', 'Клиент')], max_length=20, null=True, verbose_name='Предыдущая роль'),
        ),
    ]
