# Generated by Django 5.2.4 on 2025-07-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='previous_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Главный администратор'), ('autoservice_admin', 'Администратор автосервиса'), ('manager', 'Менеджер'), ('master', 'Мастер'), ('client', 'Клиент')], max_length=20, null=True, verbose_name='Предыдущая роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Главный администратор'), ('autoservice_admin', 'Администратор автосервиса'), ('manager', 'Менеджер'), ('master', 'Мастер'), ('client', 'Клиент')], default='client', max_length=20, verbose_name='Роль'),
        ),
    ]
