# Generated by Django 5.2.4 on 2025-07-27 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг для URL')),
                ('icon', models.CharField(blank=True, help_text='Например: bi-gear, bi-car-front и т.д.', max_length=50, verbose_name='Bootstrap Icon класс')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StandardService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Стандартное название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг для URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('typical_duration_min', models.PositiveIntegerField(help_text='Минимальное время выполнения', verbose_name='Мин. длительность (мин)')),
                ('typical_duration_max', models.PositiveIntegerField(help_text='Максимальное время выполнения', verbose_name='Макс. длительность (мин)')),
                ('typical_price_min', models.DecimalField(blank=True, decimal_places=2, help_text='Ориентировочная минимальная цена', max_digits=10, null=True, verbose_name='Мин. цена (руб.)')),
                ('typical_price_max', models.DecimalField(blank=True, decimal_places=2, help_text='Ориентировочная максимальная цена', max_digits=10, null=True, verbose_name='Макс. цена (руб.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_services', to='core.servicecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Стандартная услуга',
                'verbose_name_plural': 'Стандартные услуги',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена в рублях', max_digits=10, verbose_name='Цена (руб.)')),
                ('duration', models.PositiveIntegerField(default=30, help_text='Время выполнения в минутах', verbose_name='Длительность (мин)')),
                ('is_popular', models.BooleanField(default=False, help_text='Отмечать популярные услуги для выделения', verbose_name='Популярная услуга')),
                ('is_active', models.BooleanField(default=True, help_text='Доступна ли услуга для заказа', verbose_name='Активна')),
                ('image', models.ImageField(blank=True, help_text='Фото для демонстрации услуги', upload_to='services/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('autoservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.autoservice', verbose_name='Автосервис')),
                ('standard_service', models.ForeignKey(blank=True, help_text='Выберите из справочника для возможности сравнения с другими автосервисами', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoservice_services', to='core.standardservice', verbose_name='Стандартная услуга')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-is_popular', 'name'],
                'unique_together': {('autoservice', 'name')},
            },
        ),
    ]
