# Generated by Django 5.2.4 on 2025-07-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicecategory_standardservice_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardservice',
            name='typical_duration_max',
        ),
        migrations.RemoveField(
            model_name='standardservice',
            name='typical_duration_min',
        ),
        migrations.RemoveField(
            model_name='standardservice',
            name='typical_price_max',
        ),
        migrations.RemoveField(
            model_name='standardservice',
            name='typical_price_min',
        ),
    ]
