# Generated by Django 5.2.4 on 2025-07-28 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_typical_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Телефон клиента')),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email клиента')),
                ('car_brand', models.CharField(max_length=50, verbose_name='Марка автомобиля')),
                ('car_model', models.CharField(max_length=50, verbose_name='Модель автомобиля')),
                ('car_year', models.PositiveIntegerField(help_text='Год выпуска автомобиля', verbose_name='Год выпуска')),
                ('car_number', models.CharField(blank=True, help_text='Государственный номер автомобиля (необязательно)', max_length=15, verbose_name='Госномер')),
                ('description', models.TextField(blank=True, help_text='Опишите проблему или особые пожелания', verbose_name='Описание проблемы')),
                ('preferred_date', models.DateField(help_text='Когда вам удобно привезти автомобиль', verbose_name='Предпочтительная дата')),
                ('preferred_time', models.TimeField(help_text='Во сколько вам удобно приехать', verbose_name='Предпочтительное время')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('in_progress', 'В работе'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус заказа')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Окончательная стоимость (может отличаться от базовой цены услуги)', max_digits=10, verbose_name='Итоговая цена')),
                ('estimated_duration', models.PositiveIntegerField(help_text='Время выполнения в минутах', verbose_name='Оценочное время выполнения (мин)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('admin_notes', models.TextField(blank=True, help_text='Внутренние заметки для сотрудников', verbose_name='Комментарии автосервиса')),
                ('autoservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.autoservice', verbose_name='Автосервис')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
