# Generated by Django 5.2.4 on 2025-07-29 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_order_client_email_remove_order_client_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('number', models.CharField(blank=True, help_text='Государственный номер автомобиля (необязательно)', max_length=15, verbose_name='Госномер')),
                ('is_default', models.BooleanField(default=False, help_text='Будет выбираться автоматически при создании заказов', verbose_name='Основной автомобиль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-is_default', '-created_at'],
                'unique_together': {('owner', 'brand', 'model', 'year')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(blank=True, help_text='Выберите из сохраненных автомобилей или оставьте пустым для ввода вручную', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.car', verbose_name='Автомобиль из профиля'),
        ),
    ]
