# Generated by Django 5.2.4 on 2025-07-31 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_master',
            field=models.ForeignKey(blank=True, help_text='Мастер, назначенный на выполнение заказа', limit_choices_to={'role': 'master'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный мастер'),
        ),
    ]
