# Generated by Django 5.2.4 on 2025-08-01 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_assigned_master'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('weekly', 'Еженедельный график'), ('monthly', 'Месячный график'), ('custom', 'Индивидуальный график')], default='weekly', max_length=20, verbose_name='Тип графика')),
                ('start_date', models.DateField(help_text='С какой даты действует график', verbose_name='Дата начала действия')),
                ('end_date', models.DateField(blank=True, help_text='До какой даты действует график (пустое поле = бессрочно)', null=True, verbose_name='Дата окончания действия')),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], null=True, verbose_name='День недели')),
                ('specific_date', models.DateField(blank=True, null=True, verbose_name='Конкретная дата')),
                ('is_working_day', models.BooleanField(default=True, help_text='Отметьте, если это рабочий день', verbose_name='Рабочий день')),
                ('start_time', models.TimeField(blank=True, help_text='Во сколько начинается рабочий день', null=True, verbose_name='Время начала работы')),
                ('end_time', models.TimeField(blank=True, help_text='Во сколько заканчивается рабочий день', null=True, verbose_name='Время окончания работы')),
                ('break_start', models.TimeField(blank=True, help_text='Время начала обеденного перерыва', null=True, verbose_name='Начало перерыва')),
                ('break_end', models.TimeField(blank=True, help_text='Время окончания обеденного перерыва', null=True, verbose_name='Конец перерыва')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о графике', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('master', models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
                'ordering': ['master__first_name', 'master__last_name', 'start_date'],
            },
        ),
    ]
