# Generated by Django 5.2.4 on 2025-08-01 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_workschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='custom_days',
            field=models.CharField(blank=True, help_text='Дни недели через запятую: 1-Пн, 2-Вт, 3-Ср, 4-Чт, 5-Пт, 6-Сб, 7-Вс', max_length=50, verbose_name='Дни недели'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активные графики используются для расчета загрузки', verbose_name='Активный график'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='end_time',
            field=models.TimeField(help_text='Во сколько заканчивается рабочий день', verbose_name='Время окончания работы'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='master',
            field=models.ForeignKey(help_text='Мастер, для которого создается график', limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='schedule_type',
            field=models.CharField(choices=[('weekly', 'Еженедельный'), ('monthly', 'Месячный'), ('custom', 'Индивидуальный')], default='weekly', max_length=20, verbose_name='Тип графика'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='start_time',
            field=models.TimeField(help_text='Во сколько начинается рабочий день', verbose_name='Время начала работы'),
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='break_end',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='break_start',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='is_working_day',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='specific_date',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='weekday',
        ),
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together={('master', 'schedule_type', 'start_date', 'custom_days')},
        ),
    ]
