# Generated by Django 5.2.4 on 2025-08-02 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_custom_fields_to_workschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preferred_master',
            field=models.ForeignKey(blank=True, help_text='Мастер, которого предпочел клиент', limit_choices_to={'role': 'master'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_orders', to=settings.AUTH_USER_MODEL, verbose_name='Предпочитаемый мастер'),
        ),
    ]
