# Generated by Django 5.2.4 on 2025-08-02 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_preferred_master'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('autoservice', 'Отзыв об автосервисе'), ('master', 'Отзыв о мастере'), ('manager', 'Отзыв о менеджере'), ('administrator', 'Отзыв об администраторе'), ('service', 'Отзыв об услуге'), ('client', 'Отзыв о клиенте')], max_length=20, verbose_name='Тип отзыва')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '⭐ Очень плохо'), (2, '⭐⭐ Плохо'), (3, '⭐⭐⭐ Нормально'), (4, '⭐⭐⭐⭐ Хорошо'), (5, '⭐⭐⭐⭐⭐ Отлично')], verbose_name='Оценка')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок отзыва')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('pros', models.TextField(blank=True, help_text='Что понравилось', verbose_name='Плюсы')),
                ('cons', models.TextField(blank=True, help_text='Что не понравилось', verbose_name='Минусы')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Анонимный отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва')),
                ('autoservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.autoservice', verbose_name='Автосервис')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.order', verbose_name='Связанный заказ')),
                ('reviewed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (мастер/менеджер/админ/клиент)')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_replies', to=settings.AUTH_USER_MODEL, verbose_name='Автор ответа')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='core.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Ответ на отзыв',
                'verbose_name_plural': 'Ответы на отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['review_type', 'is_approved'], name='core_review_review__c23e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating', 'created_at'], name='core_review_rating_528231_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['autoservice', 'is_approved'], name='core_review_autoser_8664f2_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewed_user', 'is_approved'], name='core_review_reviewe_12eb75_idx'),
        ),
    ]
