# Generated by Django 5.2.4 on 2025-08-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_review_reviewreply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок отзыва'),
        ),
    ]
