# Generated by Django 5.2.4 on 2025-08-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата одобрения'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='Отклонён'),
        ),
        migrations.AddField(
            model_name='review',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отклонения'),
        ),
    ]
