# Generated by Django 5.2.4 on 2025-08-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_review_approved_at_review_is_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review_left',
            field=models.BooleanField(default=False, help_text='Отметка о том, что клиент оставил отзыв по данному заказу', verbose_name='Отзыв оставлен'),
        ),
    ]
