# Generated by Django 5.2.4 on 2025-08-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_review_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время завершения заказа', null=True, verbose_name='Дата завершения'),
        ),
    ]
