# Generated by Django 5.2.4 on 2025-08-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_order_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoservice',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='autoservice',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='autoservice',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='autoservice',
            name='address',
            field=models.TextField(blank=True, help_text='Автоматически формируется из города, улицы и дома', verbose_name='Адрес (полный)'),
        ),
    ]
