# Generated by Django 5.2.4 on 2025-08-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_split_address_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoservice',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Дома'),
        ),
    ]
