# Generated by Django 5.2.4 on 2025-08-09 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_split_address_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoServicePageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_ip', models.GenericIPAddressField(help_text='IP адрес пользователя, посетившего страницу', verbose_name='IP адрес посетителя')),
                ('user_agent', models.TextField(blank=True, help_text='Информация о браузере пользователя', verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, help_text='URL страницы, с которой пришел пользователь', max_length=500, verbose_name='Откуда пришел')),
                ('page_url', models.URLField(help_text='Полный URL посещенной страницы', max_length=500, verbose_name='URL страницы')),
                ('session_key', models.CharField(blank=True, help_text='Ключ сессии для идентификации уникального посетителя', max_length=40, verbose_name='Ключ сессии')),
                ('visit_date', models.DateField(auto_now_add=True, help_text='Дата посещения страницы', verbose_name='Дата посещения')),
                ('visit_time', models.DateTimeField(auto_now_add=True, help_text='Точное время посещения страницы', verbose_name='Время посещения')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Время, проведенное на странице в секундах', null=True, verbose_name='Время на странице (сек)')),
                ('is_unique_visitor', models.BooleanField(default=True, help_text='Первое посещение этого автосервиса данным пользователем за день', verbose_name='Уникальный посетитель')),
                ('is_bounce', models.BooleanField(default=False, help_text='Пользователь покинул сайт с этой страницы без перехода на другие', verbose_name='Отказ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('autoservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_visits', to='core.autoservice', verbose_name='Автосервис')),
                ('user', models.ForeignKey(blank=True, help_text='Авторизованный пользователь (если есть)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoservice_visits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Посещение страницы автосервиса',
                'verbose_name_plural': 'Посещения страниц автосервисов',
                'ordering': ['-visit_time'],
                'indexes': [models.Index(fields=['autoservice', 'visit_date'], name='core_autose_autoser_61d03b_idx'), models.Index(fields=['visitor_ip', 'visit_date'], name='core_autose_visitor_e40ce9_idx'), models.Index(fields=['user', 'visit_date'], name='core_autose_user_id_dc0032_idx'), models.Index(fields=['session_key', 'visit_date'], name='core_autose_session_3c6c54_idx'), models.Index(fields=['visit_date'], name='core_autose_visit_d_954902_idx'), models.Index(fields=['is_unique_visitor'], name='core_autose_is_uniq_7148d4_idx')],
            },
        ),
    ]
