# Название нашего workflow для отображения в интерфейсе GitHub
name: Deploy to VPS

# Указываем когда запускать - при push в main ветку
on:
  push:
    branches: [ main ]

# Определяем задачи для выполнения 
jobs:
  deploy:
    # Указываем на какой ОС запускать
    runs-on: ubuntu-latest

    steps:
      # Получаем код из репозитория
      - uses: actions/checkout@v3

      # Деплоим на сервер через SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          # Используем секреты из GitHub для подключения
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

          # Команды выполняемые на сервере
          script: |
            # Переходим в директорию проекта
            cd /home/koddex/Diploma

            # Останавливаем службу приложения
            echo "${{ secrets.PASSWORD }}" | sudo -S systemctl stop diploma

            # Обновляем код из репозитория (без sudo)
            git pull

            # Если у вас Poetry
            /home/koddex/.local/bin/poetry install --no-root

            # Применяем миграции (если нужно)
            /home/koddex/.local/bin/poetry run python manage.py migrate

            # Создаем файл .env из секрета
            echo "${{ secrets.ENV_FILE }}" > .env

            # Собираем статические файлы (если нужно)
            /home/koddex/.local/bin/poetry run python manage.py collectstatic --noinput

            # Перезапускаем systemd сервис
            echo "${{ secrets.PASSWORD }}" | sudo -S systemctl start diploma
